### ISSUE TITLE
VLarn

### ISSUE THREAD

**Issue by johnsonjh** [primeau/Larn#8]
Hi there - For some years I've maintained [VLarn](https://github.com/johnsonjh/vlarn), which is essentially just a re-balancing and clean-up based on Julian's Amiga ULarn - you might want to add to your very cool Larn website.

**Comment by primeau** [comment]
Hi -- sorry for the late response. I'd be happy to add a link on larn.org. Can you give me a description in about ~50 chars for how you'd like it to be described?

**Comment by johnsonjh** [comment]
The biggest thing I did with VLarn was try to balance the game a bit for new players and eliminate some complaints while actually improving things - based on the Amiga ULarn from Julian ... mostly stealing from my own README, I've adjusted maps to not require diagonal movements, which resulted in slightly extending the time limits and tweaking the player carrying capacity. Dealer McDope's pad has been removed, and the lemmings in the game have been made much less aggressive - the rest is boring, non-player-facing changes, mostly.

In fact, I had initially *completely* changed things around, but decided that this changed the feel of the game too much, and the more radical versions of VLarn weren't publicly released.  The *classic* behavior of the lemmings, however, always bothered me.  Look at https://www.reddit.com/r/roguelikes/comments/fo51zv/browserbased_ularn/ and see the comments there. It bothered others too.

It seems that getting to Level 77 by just killing lemmings - or having to waste time killing them - or worse "farming" them to get a bunch of experience right away - is more of a loophole than a feature. Getting rid of that, or at least toning that down very early in the game results in a different strategy needed early on, and a bit more care at the beginning of a game.

Some players might like this, and some might not!  Regardless, these small re-balancing changes **do** change the character of the game-play enough that I believe calling it a new version of ULarn would be dishonest, so VLarn was born.  Also, a random note, I've talked to Julian' a few times - but not recently and not since COVID..  He was working on an update to Amiga Ularn, but I've not followed up with him since then, unfortunately.

I should - Larn is kind of a small world.

So, anyway, for a short description?

"VLarn is based on Amiga ULarn with modifications to balance game-play" 

Hopefully that isn't too long.  

It would be neat to see VLarn playable with the graphics tile mode in the browser.  Maybe one day I'll look into emscripten or whatever you used to do the port....

**Comment by primeau** [comment]
Apologies for the delay, I've finally added a link to VLarn to larn.org

A few other comments (feel free to email eye@larn.org to continue the chat!):
- removing diagonals seems pretty extreme. what was the motivation for that?
- i think lemmings are stupid too, but i was never a ularn player growing up so i was hesitant to change anything there
- i'd love to know what balance changes you made. i'm always looking for ways to make the game more playable at higher difficulties
- no emscripten here, i re-write the code from scratch, borrowing very heavily from the original C code
